export const translations = {
  en: {
    about: 'About',
    education: 'Education',
    skills: 'Skills',
    experience: 'Experience',
    portfolio: 'Portfolio',
    achievements: 'Achievements',
    services: 'Services',
    testimonials: 'Testimonials',
    contact: 'Contact',
    sendMessage: 'Send Message',
    yourName: 'Your Name',
    yourEmail: 'Your Email',
    yourMessage: 'Your Message',
    astronaut: 'Astronaut',
    'astronaut-desc': 'Venturing into the unknown and pushing the boundaries of human exploration.',
    universe: 'Universe',
    'universe-desc': 'Exploring the vastness of space and the wonders of the cosmos.',
    viewMoreProjects: 'View more projects by Thanh Long',
    aiAssistant: 'AI Assistant',
    askMeAnything: 'Ask me anything...',
    toggleAI: 'Toggle AI',
    developedBy: 'Designed with ♥ by Quách Thành Long',
  },
  vi: {
    about: 'Giới thiệu',
    education: 'Học vấn',
    skills: 'Kỹ năng',
    experience: 'Kinh nghiệm',
    portfolio: 'Dự án',
    achievements: 'Thành tựu',
    services: 'Dịch vụ',
    testimonials: 'Nhận xét',
    contact: 'Liên hệ',
    sendMessage: 'Gửi',
    yourName: 'Tên của bạn',
    yourEmail: 'Email của bạn',
    yourMessage: 'Nội dung tin nhắn',
    astronaut: 'Phi hành gia',
    'astronaut-desc': 'Dấn thân vào những điều chưa biết và đẩy lùi ranh giới khám phá của con người.',
    universe: 'Vũ trụ',
    'universe-desc': 'Khám phá sự rộng lớn của không gian và những kỳ quan của vũ trụ.',
    viewMoreProjects: 'Xem thêm dự án của Thành Long',
    aiAssistant: 'Trợ lý AI',
    askMeAnything: 'Hỏi tôi bất kỳ điều gì...',
    toggleAI: 'Bật/tắt AI',
    developedBy: 'Thiết kế với ♥ bởi Quách Thành Long',
  }
};
